name = "vein"
version = "0.1.0"
description = ""

[server]
port = 3000
workers = 16
host = "127.0.0.1"

[lua]
version = "5.4"
entry = "app.lua"

[dependencies]

[scripts]
test = "coppermoon tests/init.lua"
