[package]
name = "coppermine"
version = "0.1.0"
description = "Documentation for CopperMoon ecosystem"
author = "CopperMoon Team"
license = "MIT"
repository = ""
keywords = []
main = "app.lua"

[dependencies.tailwind]
version = "0.1.0"

[dependencies.honeymoon]
version = "0.1.0"

[dependencies.vein]
version = "0.2.0"

[dependencies.ember]
version = "0.1.0"

[dependencies.lantern]
version = "0.1.1"

[dev-dependencies]

[scripts]
